### ISSUE TITLE
提示订单号码已存在

### ISSUE THREAD

**Issue by izhangxm** [fakajun/fakajun_whmcs#1]
![image](https://user-images.githubusercontent.com/16874796/43063561-c2fb6ade-8e8e-11e8-852e-cc1af32bb826.png)

而后端调试时发现订单号码竟然是2
![image](https://user-images.githubusercontent.com/16874796/43063619-f448c618-8e8e-11e8-8d27-ce65caeb7acf.png)

再进一步调试系统传入的$param，发现没有ordernum
![image](https://user-images.githubusercontent.com/16874796/43063716-33285a2e-8e8f-11e8-878b-3a13409c186e.png)

我的whmcs的版本是7.5.2，请问发卡君，这个问题如何解决呢？

**Comment by onesez** [comment]
这是啥子编程软件的界面，好像还可以

**Comment by onesez** [comment]
phpstrom

**Comment by onesez** [comment]
修复了这个问题，再试试！
